### ISSUE TITLE
 Show Tracker and Issue ID in the selected tasks and Search Result

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/Lazymine#11] opened 2015-05-26 16:16 UTC

**Comment by AwadMaharoof** [comment] 2015-06-03 18:03
@isuru88 @Raathigesh @yohangz @chathuranga : Currently search results are ordered as:
1. Project name
2. Issue subject

What if we switch this order? As its the subject that an user will look at first and not the project name

**Comment by chathuranga** [comment] 2015-06-04 04:57
The reason we thought in this way is, when user looks at the results, he can easily decide to skip the tasks in the same project seen close by.

**Comment by isuru88** [comment] 2015-06-04 05:08
But the problem is that when a new task is added to the list, it goes to the middle. Which is a bit confusing.

**Comment by AwadMaharoof** [comment] 2015-06-04 05:21
@chathuranga , If I'm not mistaken a majority of the users would be assigned only to a single project, therefore I feel using the subject as the initial identifier would be more user friendly. Any thoughts?

**Comment by chathuranga** [comment] 2015-06-04 05:46
OK this was sorted in thinking of future task grouping as well. Let's change it to the usable manner as you feel.

**Comment by AwadMaharoof** [comment] 2015-06-04 08:53
Tracker and issue ID are not visible in search results. Order remains unchanged. Lets switch this in a future release based on user feedback.

Fixed with b85f64e0a05bbdfd750df1c6b95904418b5bc096

**Closed as completed by AwadMaharoof** 2015-06-04 08:53 UTC
Labels: enhancement, Priority 4
