### ISSUE TITLE
Date gets reset to default if set while data is fetching

### ISSUE THREAD

**Issue by yohangz** [Raathigesh/Lazymine#49] opened 2015-06-06 07:35 UTC
1. Load application
2. While data is fetching change the date.

Current Behavior: Date gets reset to default.
Expected Behavior: User changed date should remain.

**Comment by Raathigesh** [comment] 2015-06-06 07:37
Duplicate of #47

**Comment by isuru88** [comment] 2015-06-06 07:37
Duplicate of #47.

**Closed as completed** 2015-06-06 07:37 UTC
Labels: Bug, duplicate, wontfix, Priority 5
